sudo: required
dist: trusty

language: cpp
compiler: gcc

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq qtbase5-dev-tools qtdeclarative5-dev

script:
  - qmake . -recursive
  - make

after_success:
  - echo "success"
 
after_failure:
  - echo "failure"
